PUT http://localhost:8080/api/seats/assign
Content-Type: application/json

{
  "empId": "10002",
  "seatSeq": 2
}

###

GET http://localhost:8080/api/employees
###

PUT http://localhost:8080/api/seats/clear/10002

###

GET http://localhost:8080/api/employees